name: card_stack_swiper

description: A highly customizable and smooth card stack swiper widget for Flutter, supporting interactive gestures and programmatic control.

homepage: https://github.com/Politanskyi/card_stack_swiper

issue_tracker: https://github.com/Politanskyi/card_stack_swiper/issues

version: 1.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

screenshots:
  - description: "Example of the widget."
    path: images/swipe.gif